### ISSUE TITLE
Add .monster TLD

### ISSUE THREAD

**Issue by ricalamino** [SaraVieira/tld.party#8]
Time to add .monster TLD on list.

**Comment by SaraVieira** [comment]
Is that a thing? That is amazing and I live for this

**Comment by ricalamino** [comment]
Yes... **.monster** is now available... E nós podemos falar português pois sou brasileiro...

**Comment by SaraVieira** [comment]
Hey

Esqueci me completamente dist mas adicionei hoje :D
